# 5.3.7 Распространение исключений (propagation exceptions)

Подвиг 7. В программе выполняется считывание числовых данных из входного потока, командой:

```python
digits = list(map(float, input().split()))
```

Эти данные следует представить в виде объекта класса `TupleLimit`. Сам класс должен наследоваться от класса `tuple`, а
его объекты создаваться командой:

```python
tl = TupleLimit(lst, max_length)
```

где `lst` - коллекция (список или кортеж) из данных; `max_length` - максимально допустимая длина коллекции `TupleLimit`.
Если длина `lst` превышает значение `max_length`, то должно генерироваться исключение командой:

```python
raise ValueError('число элементов коллекции превышает заданный предел')
```

В самом классе `TupleLimit` переопределить магические методы `__str__()` и `__repr__()` для отображения объекта
класса `TupleLimit` в виде строки из набора данных `lst`, записанных через пробел. Например:

```python
"1.0 2.5 -5.0 11.2"
```

Создайте в программе объект класса `TupleLimit` для прочитанных данных `digits` и параметром `max_length = 5`. Выведите
на экран объект в случае его успешного создания. Иначе, выведите сообщение обработанного исключения.

Sample Input:

```python
1 2 3 4 5
```

Sample Output:

```python
1.0 2.0 3.0 4.0 5.0
```

# Solution

```python
class TupleLimit(tuple):
    def __init__(self, lst, max_length):
        self.max_length = max_length
        self.lst = lst
        if max_length < len(lst):
            raise ValueError('число элементов коллекции превышает заданный предел')
    def __new__ (cls, lst, max_length):
        return super(TupleLimit, cls).__new__(cls, tuple(lst))
    def __str__(self):
        return ' '.join(map(str, self))

    def __repr__(self):
        return ' '.join(map(str, self))


digits = list(map(float, input().split()))  # эту строчку не менять (коллекцию digits также не менять)

try:
    print(TupleLimit(digits, 5))
except ValueError as v:
    print(v)
```